name: Security audit
on: [push, pull_request]
jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.76.0
      - name: Install cargo audit compatible with toolchain
        run: cargo install cargo-audit --locked --version 0.21.1
      - name: Run cargo audit
        run: cargo audit
